"""create all

Revision ID: d981365cbe8
Revises: None
Create Date: 2015-06-24 20:49:06.760228

"""

# revision identifiers, used by Alembic.
revision = 'd981365cbe8'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contest',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Title', sa.String(length=128), nullable=True),
    sa.Column('Begin_time', sa.DateTime(), nullable=True),
    sa.Column('End_time', sa.DateTime(), nullable=True),
    sa.Column('Openness', sa.Integer(), nullable=True),
    sa.Column('Manager', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contest_Begin_time'), 'contest', ['Begin_time'], unique=False)
    op.create_index(op.f('ix_contest_End_time'), 'contest', ['End_time'], unique=False)
    op.create_table('problems',
    sa.Column('SID', sa.Integer(), nullable=False),
    sa.Column('OJ_ID', sa.String(length=64), nullable=True),
    sa.Column('PID', sa.Integer(), nullable=True),
    sa.Column('Title', sa.String(length=128), nullable=True),
    sa.Column('Total_Submissions', sa.Integer(), nullable=True),
    sa.Column('Accepted', sa.Integer(), nullable=True),
    sa.Column('LastUpdate', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('SID')
    )
    op.create_index(op.f('ix_problems_LastUpdate'), 'problems', ['LastUpdate'], unique=False)
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('default', sa.Boolean(), nullable=True),
    sa.Column('permissions', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_roles_default'), 'roles', ['default'], unique=False)
    op.create_table('status',
    sa.Column('RunID', sa.Integer(), nullable=False),
    sa.Column('user', sa.String(length=64), nullable=True),
    sa.Column('OJ_ID', sa.String(length=64), nullable=True),
    sa.Column('PID', sa.Integer(), nullable=True),
    sa.Column('SID', sa.Integer(), nullable=True),
    sa.Column('RemoteID', sa.String(length=64), nullable=True),
    sa.Column('Result', sa.String(length=64), nullable=True),
    sa.Column('Memory', sa.String(length=64), nullable=True),
    sa.Column('Time', sa.String(length=64), nullable=True),
    sa.Column('Language', sa.String(length=64), nullable=True),
    sa.Column('Code_Length', sa.String(length=64), nullable=True),
    sa.Column('CEfile', sa.String(length=64), nullable=True),
    sa.Column('Submit_Time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('RunID')
    )
    op.create_index(op.f('ix_status_Submit_Time'), 'status', ['Submit_Time'], unique=False)
    op.create_table('Contest_Problems',
    sa.Column('problems_SID', sa.Integer(), nullable=False),
    sa.Column('Contest_id', sa.Integer(), nullable=False),
    sa.Column('Add_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['Contest_id'], ['contest.id'], ),
    sa.ForeignKeyConstraint(['problems_SID'], ['problems.SID'], ),
    sa.PrimaryKeyConstraint('problems_SID', 'Contest_id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=64), nullable=True),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('confirmed', sa.Boolean(), nullable=True),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('country', sa.String(length=64), nullable=True),
    sa.Column('about_me', sa.Text(), nullable=True),
    sa.Column('member_since', sa.DateTime(), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.Column('avatar_hash', sa.String(length=32), nullable=True),
    sa.Column('school', sa.String(length=64), nullable=True),
    sa.Column('account_POJ', sa.String(length=64), nullable=True),
    sa.Column('password_POJ', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('AC_problems',
    sa.Column('AC_problems_SID', sa.Integer(), nullable=False),
    sa.Column('AC_user_id', sa.Integer(), nullable=False),
    sa.Column('AC_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['AC_problems_SID'], ['problems.SID'], ),
    sa.ForeignKeyConstraint(['AC_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('AC_problems_SID', 'AC_user_id')
    )
    op.create_table('follows',
    sa.Column('follower_id', sa.Integer(), nullable=False),
    sa.Column('followed_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('follower_id', 'followed_id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('follows')
    op.drop_table('AC_problems')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('Contest_Problems')
    op.drop_index(op.f('ix_status_Submit_Time'), table_name='status')
    op.drop_table('status')
    op.drop_index(op.f('ix_roles_default'), table_name='roles')
    op.drop_table('roles')
    op.drop_index(op.f('ix_problems_LastUpdate'), table_name='problems')
    op.drop_table('problems')
    op.drop_index(op.f('ix_contest_End_time'), table_name='contest')
    op.drop_index(op.f('ix_contest_Begin_time'), table_name='contest')
    op.drop_table('contest')
    ### end Alembic commands ###
