"""change ac_Pcepted_problem

Revision ID: 1322f39008d8
Revises: 13a824b0548f
Create Date: 2015-06-22 17:49:42.926771

"""

# revision identifiers, used by Alembic.
revision = '1322f39008d8'
down_revision = '13a824b0548f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
