"""Add status

Revision ID: 14d4c3385562
Revises: 38c1ae4fed6e
Create Date: 2015-06-19 20:49:20.951636

"""

# revision identifiers, used by Alembic.
revision = '14d4c3385562'
down_revision = '38c1ae4fed6e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('status',
    sa.Column('SID', sa.Integer(), nullable=False),
    sa.Column('user', sa.String(length=64), nullable=True),
    sa.Column('OJ_ID', sa.String(length=64), nullable=True),
    sa.Column('PID', sa.Integer(), nullable=True),
    sa.Column('Result', sa.String(length=64), nullable=True),
    sa.Column('Memory', sa.String(length=64), nullable=True),
    sa.Column('Time', sa.String(length=64), nullable=True),
    sa.Column('Language', sa.String(length=64), nullable=True),
    sa.Column('Code_Length', sa.String(length=64), nullable=True),
    sa.Column('Submit_Time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('SID')
    )
    op.create_index(op.f('ix_status_Submit_Time'), 'status', ['Submit_Time'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_status_Submit_Time'), table_name='status')
    op.drop_table('status')
    ### end Alembic commands ###
