"""Change country default

Revision ID: 367c70936e5f
Revises: 461a7110145a
Create Date: 2015-06-16 19:51:02.618179

"""

# revision identifiers, used by Alembic.
revision = '367c70936e5f'
down_revision = '461a7110145a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
