"""AdChange DB

Revision ID: 3cd91afcd1ac
Revises: 30365e3b131b
Create Date: 2015-06-22 15:21:15.062704

"""

# revision identifiers, used by Alembic.
revision = '3cd91afcd1ac'
down_revision = '30365e3b131b'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('contests')
    op.add_column('status', sa.Column('RunID', sa.Integer(), nullable=False))
    op.alter_column('status', 'SID',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('status', 'SID',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.drop_column('status', 'RunID')
    op.create_table('contests',
    sa.Column('contest_id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('contest_title', mysql.VARCHAR(length=128), nullable=True),
    sa.Column('contest_password', mysql.VARCHAR(length=64), nullable=True),
    sa.Column('contest_Openness', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('begin_time', mysql.DATETIME(), nullable=True),
    sa.Column('end_time', mysql.DATETIME(), nullable=True),
    sa.Column('manager', mysql.VARCHAR(length=64), nullable=True),
    sa.PrimaryKeyConstraint('contest_id'),
    mysql_default_charset=u'latin1',
    mysql_engine=u'InnoDB'
    )
    ### end Alembic commands ###
