"""change db

Revision ID: 41ba69f23fbb
Revises: 44c908637b44
Create Date: 2015-06-22 19:05:48.644277

"""

# revision identifiers, used by Alembic.
revision = '41ba69f23fbb'
down_revision = '44c908637b44'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
