"""change db

Revision ID: 44c908637b44
Revises: 50fd049851bf
Create Date: 2015-06-22 18:19:28.809324

"""

# revision identifiers, used by Alembic.
revision = '44c908637b44'
down_revision = '50fd049851bf'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
