"""Change poj_username default

Revision ID: 461a7110145a
Revises: 2b973d44a942
Create Date: 2015-06-16 17:10:17.107284

"""

# revision identifiers, used by Alembic.
revision = '461a7110145a'
down_revision = '2b973d44a942'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
