"""change problems3

Revision ID: 4a6216fb43bc
Revises: 1bbda9f1ffd3
Create Date: 2015-06-15 21:23:19.844798

"""

# revision identifiers, used by Alembic.
revision = '4a6216fb43bc'
down_revision = '1bbda9f1ffd3'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('problems',
    sa.Column('SID', sa.Integer(), nullable=False),
    sa.Column('OJ_ID', sa.String(length=64), nullable=True),
    sa.Column('PID', sa.Integer(), nullable=True),
    sa.Column('Title', sa.String(length=128), nullable=True),
    sa.Column('Total_Submissions', sa.Integer(), nullable=True),
    sa.Column('Accepted', sa.Integer(), nullable=True),
    sa.Column('LastUpdate', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('SID')
    )
    op.create_index(op.f('ix_problems_LastUpdate'), 'problems', ['LastUpdate'], unique=False)
    op.drop_table('problem')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('problem',
    sa.Column('SID', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('OJ_ID', mysql.VARCHAR(length=64), nullable=True),
    sa.Column('PID', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('Title', mysql.VARCHAR(length=128), nullable=True),
    sa.Column('Total_Submissions', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('Accepted', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('LastUpdate', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('SID'),
    mysql_default_charset=u'latin1',
    mysql_engine=u'InnoDB'
    )
    op.drop_index(op.f('ix_problems_LastUpdate'), table_name='problems')
    op.drop_table('problems')
    ### end Alembic commands ###
