"""change problems4

Revision ID: 4e9bf0cc8adb
Revises: b4af644806d
Create Date: 2015-06-15 21:28:02.555464

"""

# revision identifiers, used by Alembic.
revision = '4e9bf0cc8adb'
down_revision = 'b4af644806d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('problems',
    sa.Column('SID', sa.Integer(), nullable=False),
    sa.Column('OJ_ID', sa.String(length=64), nullable=True),
    sa.Column('PID', sa.Integer(), nullable=True),
    sa.Column('Title', sa.String(length=128), nullable=True),
    sa.Column('Total_Submissions', sa.Integer(), nullable=True),
    sa.Column('Accepted', sa.Integer(), nullable=True),
    sa.Column('LastUpdate', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('SID')
    )
    op.create_index(op.f('ix_problems_LastUpdate'), 'problems', ['LastUpdate'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_problems_LastUpdate'), table_name='problems')
    op.drop_table('problems')
    ### end Alembic commands ###
