"""change db

Revision ID: 50fd049851bf
Revises: 1322f39008d8
Create Date: 2015-06-22 18:06:35.236800

"""

# revision identifiers, used by Alembic.
revision = '50fd049851bf'
down_revision = '1322f39008d8'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('AC_problems', sa.Column('AC_problems_SID', sa.Integer(), nullable=False))
    op.add_column('AC_problems', sa.Column('AC_user_id', sa.Integer(), nullable=False))
    op.drop_constraint(u'AC_problems_ibfk_1', 'AC_problems', type_='foreignkey')
    op.create_foreign_key(None, 'AC_problems', 'users', ['AC_user_id'], ['id'])
    op.create_foreign_key(None, 'AC_problems', 'problems', ['AC_problems_SID'], ['SID'])
    op.drop_column('AC_problems', 'problems_SID')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('AC_problems', sa.Column('problems_SID', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'AC_problems', type_='foreignkey')
    op.drop_constraint(None, 'AC_problems', type_='foreignkey')
    op.create_foreign_key(u'AC_problems_ibfk_1', 'AC_problems', 'problems', ['problems_SID'], ['SID'])
    op.drop_column('AC_problems', 'AC_user_id')
    op.drop_column('AC_problems', 'AC_problems_SID')
    ### end Alembic commands ###
