"""AdChange DB

Revision ID: 552d0c66efd
Revises: 3cd91afcd1ac
Create Date: 2015-06-22 15:29:40.799233

"""

# revision identifiers, used by Alembic.
revision = '552d0c66efd'
down_revision = '3cd91afcd1ac'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('all_status',
    sa.Column('RunID', sa.Integer(), nullable=False),
    sa.Column('user', sa.String(length=64), nullable=True),
    sa.Column('OJ_ID', sa.String(length=64), nullable=True),
    sa.Column('PID', sa.Integer(), nullable=True),
    sa.Column('SID', sa.Integer(), nullable=True),
    sa.Column('Result', sa.String(length=64), nullable=True),
    sa.Column('Memory', sa.String(length=64), nullable=True),
    sa.Column('Time', sa.String(length=64), nullable=True),
    sa.Column('Language', sa.String(length=64), nullable=True),
    sa.Column('Code_Length', sa.String(length=64), nullable=True),
    sa.Column('CEfile', sa.String(length=64), nullable=True),
    sa.Column('Submit_Time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('RunID')
    )
    op.create_index(op.f('ix_all_status_Submit_Time'), 'all_status', ['Submit_Time'], unique=False)
    op.drop_table('status')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('status',
    sa.Column('SID', mysql.INTEGER(display_width=11), server_default=sa.text(u"'0'"), autoincrement=False, nullable=False),
    sa.Column('user', mysql.VARCHAR(length=64), nullable=True),
    sa.Column('OJ_ID', mysql.VARCHAR(length=64), nullable=True),
    sa.Column('PID', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('Result', mysql.VARCHAR(length=64), nullable=True),
    sa.Column('Memory', mysql.VARCHAR(length=64), nullable=True),
    sa.Column('Time', mysql.VARCHAR(length=64), nullable=True),
    sa.Column('Language', mysql.VARCHAR(length=64), nullable=True),
    sa.Column('Code_Length', mysql.VARCHAR(length=64), nullable=True),
    sa.Column('CEfile', mysql.VARCHAR(length=64), nullable=True),
    sa.Column('Submit_Time', mysql.DATETIME(), nullable=True),
    sa.Column('RunID', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('SID'),
    mysql_default_charset=u'latin1',
    mysql_engine=u'InnoDB'
    )
    op.drop_index(op.f('ix_all_status_Submit_Time'), table_name='all_status')
    op.drop_table('all_status')
    ### end Alembic commands ###
