"""Add OJ_status

Revision ID: 5551b25238ef
Revises: d981365cbe8
Create Date: 2015-06-24 22:57:49.842864

"""

# revision identifiers, used by Alembic.
revision = '5551b25238ef'
down_revision = 'd981365cbe8'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('oj_status',
    sa.Column('OJ_ID', sa.String(length=64), nullable=False),
    sa.Column('OJ_Status', sa.Boolean(), nullable=True),
    sa.Column('Last_Update', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('OJ_ID')
    )
    op.create_index(op.f('ix_oj_status_Last_Update'), 'oj_status', ['Last_Update'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_oj_status_Last_Update'), table_name='oj_status')
    op.drop_table('oj_status')
    ### end Alembic commands ###
