"""creat add_contest

Revision ID: 95b162124d3
Revises: 41ba69f23fbb
Create Date: 2015-06-23 19:00:56.914977

"""

# revision identifiers, used by Alembic.
revision = '95b162124d3'
down_revision = '41ba69f23fbb'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Title', sa.String(length=128), nullable=True),
    sa.Column('Begin_time', sa.DateTime(), nullable=True),
    sa.Column('End_time', sa.DateTime(), nullable=True),
    sa.Column('Openness', sa.Integer(), nullable=True),
    sa.Column('Manager', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contests_Begin_time'), 'contests', ['Begin_time'], unique=False)
    op.create_index(op.f('ix_contests_End_time'), 'contests', ['End_time'], unique=False)
    op.create_table('Add_contests',
    sa.Column('Manager_ID', sa.Integer(), nullable=False),
    sa.Column('Contest_ID', sa.Integer(), nullable=False),
    sa.Column('ADD_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['Contest_ID'], ['contests.id'], ),
    sa.ForeignKeyConstraint(['Manager_ID'], ['users.id'], ),
    sa.PrimaryKeyConstraint('Manager_ID', 'Contest_ID')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Add_contests')
    op.drop_index(op.f('ix_contests_End_time'), table_name='contests')
    op.drop_index(op.f('ix_contests_Begin_time'), table_name='contests')
    op.drop_table('contests')
    ### end Alembic commands ###
