"""change problems4

Revision ID: b4af644806d
Revises: 4a6216fb43bc
Create Date: 2015-06-15 21:27:17.065031

"""

# revision identifiers, used by Alembic.
revision = 'b4af644806d'
down_revision = '4a6216fb43bc'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
